name: Check App Health

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test import and basic functionality
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python -c "
        import streamlit as st
        from config import MODEL_NAME, validate_environment
        from utils.unified_client import UnifiedAIClient
        from utils.broker_logic import AustralianMortgageBroker
        
        print('✅ All imports successful')
        print(f'Default model: {MODEL_NAME}')
        
        # Test configuration
        missing = validate_environment()
        if missing:
            print(f'⚠️ Missing env vars: {missing}')
        else:
            print('✅ Environment validation passed')
        "
