[global]

# 开发模式设置
developmentMode = false

[server]

# 服务器配置
headless = true
enableCORS = false
enableXsrfProtection = false

# 上传文件大小限制 (MB)
maxUploadSize = 200

# 启用 WebSocket 压缩
enableWebsocketCompression = true

[browser]

# 自动在浏览器中打开
gatherUsageStats = false

[theme]

# 主题配置
base = "light"
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[logger]

# 日志级别
level = "info"
